# Generated by Django 5.2.14 on 2026-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pickuppoint_order_delivery_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_gnf',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_payout_gnf',
            field=models.BigIntegerField(default=0),
        ),
    ]
