# Generated by Django 5.2.14 on 2026-07-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_livreur_fine_weekly_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='verification_code',
            field=models.CharField(help_text="Code 6 chiffres que l'acheteur fournit au livreur à la réception", max_length=6),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='fee_gnf',
            field=models.BigIntegerField(default=0, help_text='Frais de base en GNF (inclut free_km_radius et free_weight_kg)'),
        ),
        migrations.AlterField(
            model_name='livreurfine',
            name='description',
            field=models.TextField(blank=True, help_text="Détail de l'amende"),
        ),
        migrations.AlterField(
            model_name='livreurfine',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Commande liée (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreur_fines', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='livreurpayment',
            name='gross_gnf',
            field=models.BigIntegerField(help_text='Frais de livraison bruts (delivery_fee_gnf)'),
        ),
        migrations.AlterField(
            model_name='livreurpayment',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='Référence virement/OM/MTN', max_length=150),
        ),
        migrations.AlterField(
            model_name='livreurweeklypayout',
            name='fines_gnf',
            field=models.BigIntegerField(default=0, help_text='Total amendes déduites'),
        ),
        migrations.AlterField(
            model_name='livreurweeklypayout',
            name='gross_gnf',
            field=models.BigIntegerField(default=0, help_text='Total brut livraisons'),
        ),
        migrations.AlterField(
            model_name='livreurweeklypayout',
            name='net_gnf',
            field=models.BigIntegerField(default=0, help_text='Net à verser = brut - amendes'),
        ),
        migrations.AlterField(
            model_name='livreurweeklypayout',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Ex: orange_money, mtn, virement', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance de livraison en km (GPS ou saisie manuelle)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Note interne de l'admin lors du traitement"),
        ),
    ]
