# Generated by Django 5.2.14 on 2026-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_payout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Numéro Orange Money ou MTN MoMo pour recevoir les paiements', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='payout_provider',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo')], help_text='Opérateur mobile money pour les virements', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Numéro Orange Money ou MTN MoMo pour recevoir vos paiements', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payout_provider',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo')], help_text='Opérateur mobile money pour les versements', max_length=15),
        ),
    ]
