"""
Backup Guimatrix DB (Render → fichier SQL)
Double-clique pour lancer, ou: python backup_python.py
"""
import subprocess, sys, os

print("=" * 50)
print("  Backup Guimatrix - Python psycopg2")
print("=" * 50)

# Installe psycopg2 si besoin
print("\nInstallation de psycopg2...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "psycopg2-binary", "--quiet"])
import psycopg2

DB_URL = "postgresql://guineemarche_db_user:FpIC8b1kUpUfwjOeRkHa473b2bnTtWnl@dpg-d8e49dv7f7vs73cq19a0-a.frankfurt-postgres.render.com/guineemarche_db"
OUTPUT = os.path.join(os.path.dirname(__file__), "guimatrix_backup.sql")

print(f"\nConnexion a Render...")
conn = psycopg2.connect(DB_URL)
conn.autocommit = True
cur = conn.cursor()

lines = []
lines.append("-- Guimatrix DB Backup\n")
lines.append("-- Generated by backup_python.py\n\n")
lines.append("SET client_encoding = 'UTF8';\n")
lines.append("SET standard_conforming_strings = on;\n\n")

# Récupère toutes les tables
cur.execute("""
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename;
""")
tables = [row[0] for row in cur.fetchall()]
print(f"Tables trouvees: {', '.join(tables)}\n")

for table in tables:
    print(f"  Export: {table}...")

    # Schema (CREATE TABLE)
    cur.execute(f"""
        SELECT 'CREATE TABLE IF NOT EXISTS ' || quote_ident(table_name) || ' (' ||
            string_agg(
                quote_ident(column_name) || ' ' || data_type ||
                CASE WHEN character_maximum_length IS NOT NULL
                     THEN '(' || character_maximum_length || ')' ELSE '' END ||
                CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END,
                ', '
            ) || ');'
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        GROUP BY table_name;
    """, (table,))
    schema_row = cur.fetchone()
    if schema_row:
        lines.append(f"\n-- Table: {table}\n")
        lines.append(schema_row[0] + "\n")

    # Données (INSERT INTO)
    cur.execute(f'SELECT * FROM {table}')
    rows = cur.fetchall()
    if rows:
        col_names = [desc[0] for desc in cur.description]
        cols = ", ".join([f'"{c}"' for c in col_names])
        lines.append(f"\n-- Data for {table}\n")
        for row in rows:
            vals = []
            for v in row:
                if v is None:
                    vals.append("NULL")
                elif isinstance(v, bool):
                    vals.append("TRUE" if v else "FALSE")
                elif isinstance(v, (int, float)):
                    vals.append(str(v))
                else:
                    escaped = str(v).replace("'", "''")
                    vals.append(f"'{escaped}'")
            vals_str = ", ".join(vals)
            lines.append(f'INSERT INTO "{table}" ({cols}) VALUES ({vals_str});\n')

cur.close()
conn.close()

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.writelines(lines)

size_kb = os.path.getsize(OUTPUT) // 1024
print(f"\n{'=' * 50}")
print(f"  SUCCES! {OUTPUT}")
print(f"  Taille: {size_kb} Ko, {len(tables)} tables")
print(f"{'=' * 50}")
input("\nAppuyez sur Entree pour quitter...")
