# Generated by Django 5.2.14 on 2026-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='commission_pct',
            field=models.PositiveSmallIntegerField(default=4, help_text='Pourcentage prélevé sur les transactions Mobile Money en escrow.', verbose_name='Commission escrow (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='escrow_enabled',
            field=models.BooleanField(default=True, help_text='Active le flux de paiement sécurisé via Mobile Money.', verbose_name='Paiement escrow activé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_listings_enabled',
            field=models.BooleanField(default=True, help_text='Si activé, tous les utilisateurs publient sans limite (ignore les abonnements).', verbose_name='Publications gratuites illimitées'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Affiche une bannière de maintenance sur toutes les pages.', verbose_name='Mode maintenance'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_free_listings',
            field=models.PositiveSmallIntegerField(default=5, help_text="Nombre d'annonces autorisées sur le plan gratuit (si abonnements actifs).", verbose_name='Limite annonces gratuites'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_approval_required',
            field=models.BooleanField(default=True, help_text="Les nouvelles boutiques doivent être approuvées avant d'être visibles.", verbose_name='Validation boutique par admin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_contact',
            field=models.CharField(blank=True, default='', help_text='Numéro WhatsApp pour les boosts / publicités (ex: 224XXXXXXXXX).', max_length=30, verbose_name='WhatsApp contact admin'),
        ),
    ]
