from django.urls import path
from . import views

urlpatterns = [
    path('',
        views.OrderListCreateView.as_view(),
        name='order-list'),
    path('received/',
        views.SellerOrdersView.as_view(),
        name='seller-orders'),
    path('pickup-points/',
        views.PickupPointListView.as_view(),
        name='pickup-points'),
    path('meeting-zones/',
        views.MeetingZoneListView.as_view(),
        name='meeting-zones'),
    path('webhook/<str:provider>/',
        views.PaymentWebhookView.as_view(),
        name='payment-webhook'),
    # PawaPay — URLs de rappel spécifiques par type
    path('webhook/pawapay/deposits/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'pawapay_deposit'},
        name='pawapay-deposit-webhook'),
    path('webhook/pawapay/payouts/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'pawapay_payout'},
        name='pawapay-payout-webhook'),
    path('webhook/pawapay/refunds/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'pawapay_refund'},
        name='pawapay-refund-webhook'),
    path('<uuid:pk>/',
        views.OrderDetailView.as_view(),
        name='order-detail'),
    path('<uuid:pk>/pay/',
        views.InitiatePaymentView.as_view(),
        name='order-pay'),
    path('<uuid:pk>/confirm-receipt/',
        views.ConfirmReceiptView.as_view(),
        name='order-confirm-receipt'),
    path('<uuid:pk>/dispute/',
        views.DisputeView.as_view(),
        name='order-dispute'),
    path('<uuid:pk>/<str:action>/',
        views.OrderUpdateStatusView.as_view(),
        name='order-status'),

    # Admin
    path('admin/pickup-points/',
        views.AdminPickupPointView.as_view(),
        name='admin-pickup-points'),
    path('admin/pickup-points/<uuid:pk>/',
        views.AdminPickupPointDetailView.as_view(),
        name='admin-pickup-point-detail'),
    path('admin/meeting-zones/',
        views.AdminMeetingZoneView.as_view(),
        name='admin-meeting-zones'),
    path('admin/meeting-zones/<uuid:pk>/',
        views.AdminMeetingZoneDetailView.as_view(),
        name='admin-meeting-zone-detail'),
    path('admin/disputes/',
        views.AdminDisputeListView.as_view(),
        name='admin-disputes'),
    path('admin/disputes/<uuid:pk>/resolve/',
        views.AdminDisputeResolveView.as_view(),
        name='admin-dispute-resolve'),
    path('admin/stats/',
        views.AdminStatsView.as_view(),
        name='admin-stats'),
    path('admin/export/',
        views.AdminExportCSVView.as_view(),
        name='admin-export-csv'),
    path('admin/escrow/<uuid:pk>/hold/',
        views.AdminEscrowHoldView.as_view(),
        name='admin-escrow-hold'),
]
