from django.urls import path
from . import views

urlpatterns = [
    path('',
        views.OrderListCreateView.as_view(),
        name='order-list'),
    path('received/',
        views.SellerOrdersView.as_view(),
        name='seller-orders'),
    path('pickup-points/',
        views.PickupPointListView.as_view(),
        name='pickup-points'),
    path('meeting-zones/',
        views.MeetingZoneListView.as_view(),
        name='meeting-zones'),
    path('delivery-zones/',
        views.DeliveryZoneListView.as_view(),
        name='delivery-zones'),
    path('delivery-fee/',
        views.DeliveryFeeEstimateView.as_view(),
        name='delivery-fee'),
    path('zone-rates/',
        views.IntraCityZoneRateListView.as_view(),
        name='zone-rates'),
    # IMPORTANT : les routes spécifiques DOIVENT être AVANT la route générique
    # sinon Django capture tout avec webhook/<str:provider>/ et les routes ci-dessous
    # ne sont jamais atteintes.
    path('webhook/chachap/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'chachap'},
        name='chachap-webhook'),
    # Paycard Guinée — URLs de callback (doivent précéder la route générique)
    path('webhook/paycard/card/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'paycard_card'},
        name='paycard-card-webhook'),
    path('webhook/paycard/refunds/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'paycard_refund'},
        name='paycard-refund-webhook'),
    path('webhook/paycard/',
        views.PaymentWebhookView.as_view(),
        {'provider': 'paycard_payment'},
        name='paycard-payment-webhook'),
    # Route générique en dernier — capture les autres providers (orange, etc.)
    path('webhook/<str:provider>/',
        views.PaymentWebhookView.as_view(),
        name='payment-webhook'),
    path('<uuid:pk>/',
        views.OrderDetailView.as_view(),
        name='order-detail'),
    path('<uuid:pk>/pay/',
        views.InitiatePaymentView.as_view(),
        name='order-pay'),
    path('<uuid:pk>/confirm-receipt/',
        views.ConfirmReceiptView.as_view(),
        name='order-confirm-receipt'),
    path('<uuid:pk>/dispute/',
        views.DisputeView.as_view(),
        name='order-dispute'),
    path('<uuid:pk>/<str:action>/',
        views.OrderUpdateStatusView.as_view(),
        name='order-status'),

    # Livreur
    path('livreur/assignments/',
        views.LivreurOrderListView.as_view(),
        name='livreur-assignments'),
    path('livreur/assignments/<uuid:pk>/start/',
        views.LivreurStartDeliveryView.as_view(),
        name='livreur-start-delivery'),
    path('livreur/assignments/<uuid:pk>/confirm/',
        views.LivreurConfirmDeliveryView.as_view(),
        name='livreur-confirm-delivery'),

    # Admin
    path('admin/pickup-points/',
        views.AdminPickupPointView.as_view(),
        name='admin-pickup-points'),
    path('admin/pickup-points/<uuid:pk>/',
        views.AdminPickupPointDetailView.as_view(),
        name='admin-pickup-point-detail'),
    path('admin/meeting-zones/',
        views.AdminMeetingZoneView.as_view(),
        name='admin-meeting-zones'),
    path('admin/meeting-zones/<uuid:pk>/',
        views.AdminMeetingZoneDetailView.as_view(),
        name='admin-meeting-zone-detail'),
    path('admin/delivery-zones/',
        views.AdminDeliveryZoneView.as_view(),
        name='admin-delivery-zones'),
    path('admin/delivery-zones/<uuid:pk>/',
        views.AdminDeliveryZoneDetailView.as_view(),
        name='admin-delivery-zone-detail'),
    path('admin/zone-rates/',
        views.AdminIntraCityZoneRateView.as_view(),
        name='admin-zone-rates'),
    path('admin/zone-rates/<uuid:pk>/',
        views.AdminIntraCityZoneRateDetailView.as_view(),
        name='admin-zone-rate-detail'),
    path('admin/livreurs/',
        views.AdminLivreurListView.as_view(),
        name='admin-livreurs'),
    path('admin/assignments/',
        views.AdminDeliveryAssignmentListView.as_view(),
        name='admin-assignments'),
    path('admin/orders/<uuid:pk>/assign/',
        views.AdminAssignLivreurView.as_view(),
        name='admin-assign-livreur'),
    path('admin/disputes/',
        views.AdminDisputeListView.as_view(),
        name='admin-disputes'),
    path('admin/disputes/<uuid:pk>/resolve/',
        views.AdminDisputeResolveView.as_view(),
        name='admin-dispute-resolve'),
    path('admin/stats/',
        views.AdminStatsView.as_view(),
        name='admin-stats'),
    path('admin/export/',
        views.AdminExportCSVView.as_view(),
        name='admin-export-csv'),
    path('admin/escrow/<uuid:pk>/hold/',
        views.AdminEscrowHoldView.as_view(),
        name='admin-escrow-hold'),
    path('admin/orders/',
        views.AdminOrderListView.as_view(),
        name='admin-orders'),
    path('admin/assignments/<uuid:pk>/reassign/',
        views.AdminDeliveryReassignView.as_view(),
        name='admin-delivery-reassign'),

    # Comptabilité
    path('admin/accounting/summary/',
        views.AdminAccountingSummaryView.as_view(),
        name='admin-accounting-summary'),
    path('admin/accounting/livreurs/',
        views.AdminLivreurEarningsView.as_view(),
        name='admin-accounting-livreurs'),
    path('admin/accounting/livreur-payments/',
        views.AdminLivreurPaymentListView.as_view(),
        name='admin-accounting-livreur-payments'),
    path('admin/accounting/mark-paid/',
        views.AdminMarkLivreurPaidView.as_view(),
        name='admin-accounting-mark-paid'),
    path('admin/accounting/export/',
        views.AdminAccountingExportView.as_view(),
        name='admin-accounting-export'),

    # Amendes livreurs
    path('admin/accounting/fines/',
        views.AdminLivreurFineListView.as_view(),
        name='admin-fines-list'),
    path('admin/accounting/fines/create/',
        views.AdminCreateLivreurFineView.as_view(),
        name='admin-fines-create'),
    path('admin/accounting/fines/<uuid:pk>/',
        views.AdminUpdateLivreurFineView.as_view(),
        name='admin-fines-update'),

    # Virements hebdomadaires livreurs
    path('admin/accounting/weekly-payouts/',
        views.AdminWeeklyPayoutsView.as_view(),
        name='admin-weekly-payouts'),
    path('admin/accounting/weekly-payouts/mark-paid/',
        views.AdminMarkWeeklyPayoutPaidView.as_view(),
        name='admin-weekly-payouts-mark-paid'),
    path('admin/accounting/weekly-payouts/generate/',
        views.AdminGenerateWeeklyPayoutsView.as_view(),
        name='admin-weekly-payouts-generate'),

    # Retours
    path('<uuid:pk>/return/',
        views.CreateReturnView.as_view(),
        name='create-return'),
    path('admin/returns/',
        views.AdminReturnListView.as_view(),
        name='admin-returns'),
    path('admin/returns/<uuid:pk>/',
        views.AdminReturnUpdateView.as_view(),
        name='admin-return-update'),
]
